# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagename',
            field=models.TextField(default='bleh'),
        ),
    ]
