# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170923_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='~/Firefox_wallpaper.png', upload_to='static/main/'),
        ),
    ]
